github.com:
    oauth_token: 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
    user: RenaudAlly
    git_protocol: https
    users:
        RenaudAlly:
            oauth_token: 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
